name: "Build ytproxy"
on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          #- target: x86_64-pc-windows-msvc
          #  archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          #- target: x86_64-apple-darwin
          #  archive: zip
    steps:
      - uses: actions/checkout@master
      - run: sudo apt install libssl-dev
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          SRC_DIR: './mpv/scripts/ytproxy/'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: mpv/scripts/ytproxy/target/
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ytproxy binary
          automatic_release_tag: all
          prerelease: false
          files: |
            mpv/scripts/ytproxy/target/x86_64-unknown-linux-musl/release/deps/http_ytproxy-*
            mpv/scripts/ytproxy/target/x86_64-unknown-linux-gnu/release/deps/http_ytproxy-*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
